### ISSUE TITLE
Valid julia names are not accepted

### ISSUE THREAD

**Issue by aviks** [tanmaykm/JuliaWebAPI.jl#11]
This line of code
`if isempty(args) || !isalnum(args[1]) || !isalpha(args[1][1])`
means that valid julia function names with underscores returns a 404 .

**Comment by tanmaykm** [comment]
Yes.

I don't recollect anymore why that restriction was put. Most probably to reserve some namespace for use by the framework itself.

Would it be good enough if that is documented?

**Comment by aviks** [comment]
Well, I want to be able to call any valid julia method. No?

**Comment by tanmaykm** [comment]
Yes. It seems to be just a naming restriction and can be removed it if really unnecessary. But it may be useful to have a reserved namespace for things like administration and stuff.

An alias function should also let you use such names for now.

**Comment by shashi** [comment]
There is `Base.is_id_char` and `Base.is_id_start_char`

**Comment by tanmaykm** [comment]
`Base.id_id_start_char` includes unicode!

**Comment by tanmaykm** [comment]
I think we can remove this restriction and have a separate port for the internal URLs.
