### ISSUE TITLE
POST data always goes as a Dict

### ISSUE THREAD

**Issue by mdpradeep** [tanmaykm/JuliaWebAPI.jl#16]
https://github.com/tanmaykm/JuliaWebAPI.jl/blob/master/src/APIResponder.jl#L62

It is assumed here that all the APIs take only Dict type as an argument. This will force the APIs to take DICT type and convert the same to a string.

**Comment by tanmaykm** [comment]
The dict is being splatted. So this is actually not incorrect behavor.
The API method should not need to receive a dict.

Can you post some sample code?

**Comment by tanmaykm** [comment]
This is not an issue any more I think. Please reopen if it is.
