### ISSUE TITLE
Question: POST requests

### ISSUE THREAD

**Issue by EricForgy** [tanmaykm/JuliaWebAPI.jl#6]
Hi guys,

I mentioned in google groups [here](https://groups.google.com/d/msg/julia-users/Hw7pROPKyqI/UZGxeTXY270J), after Viral flagged this package, that I needed similar functionality and ended up building something myself using Morsel (before seeing JuliaBox.jl).

I am no expert for sure, but so far am happy with my Morsel server and Viral has been encouraging me to go with JuliaBox.jl instead.

Does the JuliaBox RESTServer support POST requests? I am building a web app and the Julia input data coming from the interface is too complex for parameters set in a GET request URL so I managed to get POST requests working (miraculously) with Morsel.

Also, what are some downsides you may see with Morsel as opposed to JuliaBox?

Like I mentioned to Viral recently, I am open to using this package and scrapping my own stuff if I can figure out how this works and will likely have more questions :)

**Comment by tanmaykm** [comment]
Hi. Sorry for the late response. I'm traveling and my internet access is patchy.

Yes, RESTServer should be able to extract form data from POST requests. Both query string and POST data are merged to call the APIs. I think it uses the same parser as Morsel.

Morsel should handle the request parsing pretty well, but it probably executes the handlers in-process.

JuliaBox.jl was built as a supporting package for JuliaBox (https://juliabox.org) REST APIs (hence the name). The backend (APIResponder) and HTTP frontend (RESTServer) are connected with ZMQ queues and are independent of each other.

The JuliaBox (https://juliabox.org) implementation:
- replaces the frontend with a tornado based implementation
- drives multiple Julia backends running as docker containers
- dynamically expands/contracts the pool of Julia backends based on the queue size

The RESTServer shipped with JuliaBox lacks the above scalability features, and can not be used in high volume scenarios yet. It is possible to have these in pure Julia as well, but I haven't had time to expand this beyond the JuliaBox usage. Will be glad to join hands to develop this.

**Comment by EricForgy** [comment]
Thanks Tanmay. The scalability features sound interesting and useful. I can try to help out with those, but I'm not very qualified (hasn't stopped me from trying) :)
